const projectData = [
  {
    name: "Kitty Flanagan",
    github: "",
    link: "https://kittyflanagan.com",
    src: "kitty-flanagan-website.png",
    alt: "Kitty Flanagan homepage",
    desc: "Bespoke wordpress website for comedian Kitty Flanagan",
    role: "Front End",
  },
  {
    name: "Georgie Carroll",
    github: "",
    link: "https://georgiecarroll.com",
    src: "georgie-carroll-website.png",
    alt: "Georgie Carroll homepage",
    desc: "Bespoke wordpress website for comedian Georgie Carroll",
    role: "Front End",
  },
  {
    name: "Umbilical Brothers",
    github: "",
    link: "https://umbilicalbrothers.com",
    src: "umbilical-brothers-website.png",
    alt: "Umbilical Brothers homepage",
    desc: "Bespoke wordpress website for comedians The Umbilical Brothers",
    role: "Front End",
  },
  {
    name: "Lawrence Mooney",
    github: "",
    link: "https://lawrencemooney.com",
    src: "lawrence-mooney-website.png",
    alt: "Lawrence Mooney homepage",
    desc: "Bespoke wordpress website for comedian Lawrence Mooney",
    role: "Front End",
  },
  {
    name: "Daniel Muggleton",
    github: "",
    link: "https://danielmuggleton.com.au",
    src: "daniel-muggleton-website.png",
    alt: "Daniel Muggleton homepage",
    desc: "Bespoke wordpress website for comedian Daniel Muggleton",
    role: "Front End",
  },
  {
    name: "Penguinwolf Agency",
    github: "",
    link: "https://penguinwolf.com",
    src: "penguinwolf-website.png",
    alt: "Penguinwolf homepage",
    desc: "Bespoke wordpress website for Penguinwolf Agency",
    role: "Front End",
  },
  {
    name: "Homage To Hobart",
    github: "",
    link: "https://homagetohobart.com.au",
    src: "homagetohobart.png",
    alt: "Homage to Hobart homepage",
    desc: "Business Website made with Gatsby & React",
    role: "Sole Author",
  },
  {
    name: "MCP Band",
    github: "",
    link: "https://mcptheband.com",
    src: "Home-MCP.png",
    alt: "MCP homepage",
    desc: "Band Website made with Gatsby & React",
    role: "Sole Author",
  },
  {
    name: "myradio.click",
    github: "",
    link: "https://console.myradio.click/",
    src: "console.myradio.click.png",
    alt: "myradio.click homepage",
    desc: "Radio Station Manager where stations can manage and keep track of programs. Made with React.",
    role: "Front-End",
  },
  {
    name: "Swapzie",
    github: "https://github.com/lilyso/swapzie",
    link: "https://swapzie.herokuapp.com/",
    src: "swapzie_home_page.png",
    alt: "swapzie homepage",
    desc: "A swapping platform for pre-loved toys where parents can find or donate free toys. MongoDB, Express, React, Node, Apollo, JWT.",
    role: "Sole Author",
  },
  {
    name: "Beauty Board",
    github: "https://github.com/lilyso/my-beauty-board",
    link: "https://mighty-reef-26126.herokuapp.com/",
    src: "BeautyBoardHome.png",
    alt: "beauty board homepage",
    desc: "A pinterest style platform where users can keep track of beauty products they use and share their experience with other users. Handlebars, Node, Express, MySQL, Sequelize.",
    role: "Front-End: UX, UI, Back-End: API",
  },
  {
    name: "The Techy Blog",
    github: "https://github.com/lilyso/the-techy-blog",
    link: "https://ancient-headland-48213.herokuapp.com/",
    src: "TheTechyBlog.png",
    alt: "tech blog homepage",
    desc: "A CMS-style blog site where developers can publish their blog posts. Javascript, Node, Express, MySQL, Sequelize.",
    role: "Sole Author",
  },
  {
    name: "My Weather Dashboard",
    github: "https://github.com/lilyso/weather-dashboard",
    link: "https://lilyso.github.io/weather-dashboard/",
    src: "my-weather-dashboard.png",
    alt: "weather dashboard homepage",
    desc: "A weather dashboard to track the forecast for multiple cities using the OpenWeather API.",
    role: "Sole Author",
  },
  {
    name: "Fun Night In",
    github: "https://github.com/lilyso/fun-night-in",
    link: "https://lilyso.github.io/fun-night-in/",
    src: "fun-night-in.png",
    alt: "fun night in homepage",
    desc: "Random Movie and Meal Generator. Javascript, JQuery, MealDB API, MovieDB API.",
    role: "Front-End: UX, UI",
  },
]

export default projectData
